### ISSUE TITLE
INVALID VALUE after fresh install 

### ISSUE THREAD

**Issue by utillity** [laxap/bsdist#2]
After a fresh install of BSDIST on azure with T3 6.2 and 7.6 I see the following errors when editing the HOME page (which was created by the starter package):

WEB > Page > Home > Edit Page Content "The bsdist distribution installs the extension&a..." on page "Home":
- GENERAL tab, TYPE: [ INVALID VALUE ("textpic") ]

WEB > Page > Home > Edit Page Properties:
- APPEARANCE tab, "Backend Layout (this page only)": [ INVALID VALUE ("2") ]
- APPEARANCE tab, "Backend Layout (subpages of this page)": [ INVALID VALUE ("1") ]

Any help would be greatly apprechiated.

**Comment by ewokhias** [comment]
Hi!

The first problem may be caused by TYPO3 7.6 using fluid_styled_content instead of css_styled content as default. If you go to "Extensions" in "Admin Tools", uninstall the extension "fluid_styled_content" and install the extension "css_styled_content" the first problem should be solved. 
If you need fluid_styled_content, then you have to edit each content element and change the type from "textpic" to "Text & Media". 

And for the second problem, I wasn't able to reproduce. A newly installed 7.6.10 didn't show that error.

**Comment by utillity** [comment]
Great thanks! Yes, using fluid_styled_content (I believe it's much smoother and better with bootstrap than css_styled_content). But why would the starter-package not configure that already so it works?

**Comment by ewokhias** [comment]
I guess that this has to be done yet. 
For now, the extension bootstrap_core is developed for the usage of css_styled_content.

**Comment by utillity** [comment]
ok, thanks. Maybe these 2 facts should be added to the text of the home page, so someone using bsdist for the first time does not run in to this.
